### ISSUE TITLE
Default plugin selection ignored

### ISSUE THREAD

**Issue by dmc5179** [vmware/safekeeping#3]
WHen running the safekeeping application the prompts for S3, FileStorage, and NFSStorage all show a default of false. This implies that pressing enter should be the same as typing 'false' and pressing enter. When I just press enter, I'm then prompted for the settings of each plugin. Those prompts should be skipped if the default is being applied. Here is the output where I just pressed enter at each of the 3 plugin prompt defaults for false:

```
AMAZONS3
Activate the Plugin [false]
S3 Region [us-west-2]
S3 Backet Name/folder []
S3 Access Key []
S3 Secret Key <hidden>
	Repeat password:     

FILESTORAGE
Activate the Plugin [false]
File Archive directory [/opt/vmware/safekeeping/archive]

NFSSTORAGE
Activate the Plugin [false]
NFS Absolute Path (server:/Export) [localhost:/vol]
User UID [0]
User GID [0]
Max number of retry [5]
Use port <1024 [false]
Use portmap port <1024 [false]
NFS Timeout [20]
```

**Comment by dmc5179** [comment]
Looks like even if you type false and press enter, it still asks you:
```
MAZONS3
Activate the Plugin [false]false
S3 Region [us-west-2]
S3 Backet Name/folder []
```

**Comment by mdaneri** [comment]
I know it's annoying :) 
I was lazy when I wrote this part of the code. Thanks for the feedback

**Comment by dmc5179** [comment]
I'll see if I can fix it and submit a PR.
