### ISSUE TITLE
vmbk configure does not apply changes until safekeeping is restarted

### ISSUE THREAD

**Issue by dmc5179** [vmware/safekeeping#4]
I entered the hostname of the vcenter server incorrectly during the configuration of safekeeping. After trying to run ```ivd -list``` and seeing the error I ran the configure command and changed the VMware Platform Service Controller FQDN or IP to the correct hostname. I then ran ```ivd -list``` again but got the same error message about the incorrect hostname. After closing safekeeping and starting it again the correct hostname is being used.

**Comment by mdaneri** [comment]
on 2.0 there are some new subcommand available for the configure command
```
Command: configure  -  Configure Safekeeping interactively.

Usage:
	configure  -help
	configure  -vddk <version> [-save]
	configure  -load <file> [-quiet]
	configure  -reload [-quiet]

Arguments:
  -help                     Help 
  -vddk <version>           Set Vddk Version 
  -load <file>              Load a specific configuration file 
  -save                     Save changes 
  -reload                   Reload the configuration file 
  -quiet                    No confirmation is asked. 
```

What you are asking I presume the  _-reload_ sub-command 
Am I correct?
