### ISSUE TITLE
Add support for custom vCenter port

### ISSUE THREAD

**Issue by dmc5179** [vmware/safekeeping#5]
A number of our customers have vCenter configured on a non standard port, like 8443, for various reasons. The port for safekeeping appears to be here:

./jvix/src/com/vmware/jvix/jDiskLib.java:102

Please add support for configuring the vCenter port.

**Comment by mdaneri** [comment]
I think safekeeping already has the option. let me check the code

**Comment by mdaneri** [comment]
You are right. I'm going to include the option in 2.0

**Comment by dmc5179** [comment]
Thanks!

**Comment by mdaneri** [comment]
I was checking the code. Today you can specify the port directly with the hostname.
There is no check on the hostname. For example, **myserver:8324** should works.

**Comment by dmc5179** [comment]
I believe that I did try that and it didn't work. I'll try it again and see what happens.
